### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by AMAMAM7** [neverUseThisName/Face-X-Ray#3]
Hello～Thanks for your work. But i encountered a problem 
The error is as follows:
0it [00:00, ?it/s]Traceback (most recent call last):
  File "/Users/for_am/Documents/a/FaceXRaymaster/faceBlending.py", line 174, in <module>
    main()
  File "/Users/for_am/Documents/a/FaceXRaymaster/faceBlending.py", line 42, in main
    for i, srcFace in enumerate(srcFaces):
  File "/Users/for_am/opt/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/Users/for_am/Documents/a/FaceXRaymaster/utils.py", line 31, in files
    if os.path.isfile(path):
  File "/Users/for_am/opt/anaconda3/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
**TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType**

Hope you can help me! Thanks !☺️

**Comment by neverUseThisName** [comment]
You need to have a dataset of face images and provide its path with `-sfp path/to/dataset` when running `faceBlending.py`. 
All arguments can be found in `get_args` function or by `python faceBlending.py --help`.
